-- Migration Candidate: Fix Vendors Schema
-- Generated by Antigravity
-- Purpose: Add missing JSON columns to 'vendors' table to match SQLAlchemy model.

BEGIN;

-- Add contact_info column
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS contact_info JSONB;

-- Add metadata column
-- Note: Model uses 'metadata_' attribute mapped to 'metadata' column.
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS metadata JSONB;

COMMIT;
